"""v0_1_7

Revision ID: 367564347e87
Revises: 7b673e40e96c
Create Date: 2022-05-03 09:01:57.084201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '367564347e87'
down_revision = '7b673e40e96c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receive_payment', sa.Column('bank', sa.String(length=100), nullable=True))
    op.add_column('receive_payment', sa.Column('bank_ref', sa.String(length=300), nullable=True))
    op.add_column('receive_payment', sa.Column('checkout_ref', sa.String(length=300), nullable=True))
    op.add_column('receive_payment', sa.Column('currency', sa.String(length=100), nullable=True))
    op.add_column('receive_payment', sa.Column('customer_code', sa.String(length=200), nullable=True))
    op.add_column('receive_payment', sa.Column('customer_fee', sa.Float(), nullable=True))
    op.add_column('receive_payment', sa.Column('customer_phone', sa.String(length=200), nullable=True))
    op.add_column('receive_payment', sa.Column('paid_by', sa.String(length=100), nullable=True))
    op.add_column('receive_payment', sa.Column('paid_date', sa.DateTime(), nullable=True))
    op.add_column('receive_payment', sa.Column('tnx_id', sa.String(length=100), nullable=True))
    op.drop_column('receive_payment', 'payment_type')
    op.drop_column('receive_payment', 'paid_to')
    op.drop_column('receive_payment', 'pay_by')
    op.drop_column('receive_payment', 'b24_biller_code')
    op.drop_column('receive_payment', 'fee_amount')
    op.drop_column('receive_payment', 'currency_id')
    op.drop_column('receive_payment', 'bank_id')
    op.drop_column('receive_payment', 'payment_method')
    op.drop_column('receive_payment', 'customer_org_code')
    op.drop_column('receive_payment', 'title')
    op.drop_column('receive_payment', 'company_id')
    op.drop_column('receive_payment', 'source')
    op.drop_column('receive_payment', 'payment_ref')
    op.drop_column('receive_payment', 'sync_code')
    op.drop_column('receive_payment', 'tran_date')
    op.drop_column('receive_payment', 'bank_name')
    op.drop_column('receive_payment', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receive_payment', sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('receive_payment', sa.Column('bank_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('receive_payment', sa.Column('tran_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('receive_payment', sa.Column('sync_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('receive_payment', sa.Column('payment_ref', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('receive_payment', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('receive_payment', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('receive_payment', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('receive_payment', sa.Column('customer_org_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('receive_payment', sa.Column('payment_method', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('receive_payment', sa.Column('bank_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('receive_payment', sa.Column('currency_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('receive_payment', sa.Column('fee_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('receive_payment', sa.Column('b24_biller_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('receive_payment', sa.Column('pay_by', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('receive_payment', sa.Column('paid_to', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('receive_payment', sa.Column('payment_type', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('receive_payment', 'tnx_id')
    op.drop_column('receive_payment', 'paid_date')
    op.drop_column('receive_payment', 'paid_by')
    op.drop_column('receive_payment', 'customer_phone')
    op.drop_column('receive_payment', 'customer_fee')
    op.drop_column('receive_payment', 'customer_code')
    op.drop_column('receive_payment', 'currency')
    op.drop_column('receive_payment', 'checkout_ref')
    op.drop_column('receive_payment', 'bank_ref')
    op.drop_column('receive_payment', 'bank')
    op.drop_constraint(None, 'bank', type_='unique')
    # ### end Alembic commands ###
