"""v1_0_6

Revision ID: 7b673e40e96c
Revises: 8e1ddfd38cc1
Create Date: 2022-05-02 11:56:21.565978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b673e40e96c'
down_revision = '8e1ddfd38cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receive_payment_detail')
    op.add_column('receive_payment', sa.Column('company_id', sa.INTEGER(), nullable=True))
    op.add_column('receive_payment', sa.Column('b24_biller_code', sa.String(length=100), nullable=True))
    op.add_column('receive_payment', sa.Column('bills', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receive_payment', 'bills')
    op.drop_column('receive_payment', 'b24_biller_code')
    op.drop_column('receive_payment', 'company_id')
    op.drop_constraint(None, 'bank', type_='unique')
    op.create_table('receive_payment_detail',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sync_code', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('org_code', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('customer_sync_code', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('total_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pay_amount', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('due_amount', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('txn_receive_payment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('txn_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['txn_receive_payment_id'], ['receive_payment.id'], name='receive_payment_detail_txn_receive_payment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='receive_payment_detail_pkey')
    )
    # ### end Alembic commands ###
