"""v1_0_5

Revision ID: 8e1ddfd38cc1
Revises: ad776f9dba91
Create Date: 2022-05-02 09:49:46.405893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1ddfd38cc1'
down_revision = 'ad776f9dba91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_b24', sa.Column('ar_account', sa.String(length=300), nullable=True))
    op.add_column('company_b24', sa.Column('currency', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_b24', 'currency')
    op.drop_column('company_b24', 'ar_account')
    op.drop_constraint(None, 'bank', type_='unique')
    # ### end Alembic commands ###
