"""v0_1_4

Revision ID: ad776f9dba91
Revises: d2e7845dc9dc
Create Date: 2022-04-27 10:26:19.937400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad776f9dba91'
down_revision = 'd2e7845dc9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.INTEGER(), nullable=True),
    sa.Column('total_record', sa.INTEGER(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('queue_id', sa.INTEGER(), nullable=True),
    sa.Column('b24_queue_id', sa.String(length=100), nullable=True),
    sa.Column('b24_biller_code', sa.String(length=500), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bank', type_='unique')
    op.drop_table('queue_detail')
    op.drop_table('queue')
    # ### end Alembic commands ###
