"""v0_1_9

Revision ID: b0630f8742b1
Revises: 30b30ff368f8
Create Date: 2022-05-03 09:16:47.721749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0630f8742b1'
down_revision = '30b30ff368f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receive_payment', sa.Column('b24_biller_code', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receive_payment', 'b24_biller_code')
    op.drop_constraint(None, 'bank', type_='unique')
    # ### end Alembic commands ###
