"""v0_1_3

Revision ID: d2e7845dc9dc
Revises: 61464c0b4de7
Create Date: 2022-04-25 11:05:55.819319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e7845dc9dc'
down_revision = '61464c0b4de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('settings', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.add_column('settings', sa.Column('updated_by', sa.String(length=200), nullable=True))
    op.add_column('settings', sa.Column('created_by', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'created_by')
    op.drop_column('settings', 'updated_by')
    op.drop_column('settings', 'updated_date')
    op.drop_column('settings', 'created_date')
    op.drop_constraint(None, 'bank', type_='unique')
    # ### end Alembic commands ###
